sudo: required
dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - '11'
branches:
  only:
  - travis-ci
before_script:
  - npm install
  - npm run startapi
  - npm run startweb
script:
  - npm run test:api
  - npm run test:superagent
  - npm run test:mocha
  - npm run test:chai
  - npm run test:nightwatchapi
  - npm run test:nightwatch
  - npm run test:javascript
  - npm run test:webdriverio
  - npm run test:webdriver
  - npm run test:puppeteer
  - npm run test:zombie
